color = input("Enter a color: ")
plural_noun = input("Enter a plural noun: ")
idol_name = input("Enter an idol: ")
print("Roses are " + color)
print(plural_noun + " are blue")
print("I love " + idol_name)